<?php

/**
 * ContatoPessoaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ContatoPessoaTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ContatoPessoaTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ContatoPessoa');
    }
}