<?php

/**
 * EntradaProdutoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class EntradaProdutoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object EntradaProdutoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('EntradaProduto');
    }
}