<?php

/**
 * FornecedorTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class FornecedorTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object FornecedorTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Fornecedor');
    }
}