<?php

/**
 * FuncionarioHasFuncionarioTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class FuncionarioHasFuncionarioTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object FuncionarioHasFuncionarioTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('FuncionarioHasFuncionario');
    }
}