<?php

/**
 * FuncionarioHasFuncionario1Table
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class FuncionarioHasFuncionario1Table extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object FuncionarioHasFuncionario1Table
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('FuncionarioHasFuncionario1');
    }
}