<?php

/**
 * GrupoServicoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class GrupoServicoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object GrupoServicoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('GrupoServico');
    }
}