<?php

/**
 * JuridicaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class JuridicaTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object JuridicaTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Juridica');
    }
}