<?php

/**
 * RepresentanteHasJuridica1
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ProjSymfonySisSite
 * @subpackage model
 * @author     amartos
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class RepresentanteHasJuridica1 extends BaseRepresentanteHasJuridica1
{
}
