<?php

/**
 * RepresentanteHasJuridicaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class RepresentanteHasJuridicaTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object RepresentanteHasJuridicaTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('RepresentanteHasJuridica');
    }
}