<?php

/**
 * RepresentacaoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class RepresentacaoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object RepresentacaoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Representacao');
    }
}