<?php

/**
 * ServicoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ServicoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ServicoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Servico');
    }
}