<?php

/**
 * ServicoGrupoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ServicoGrupoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ServicoGrupoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ServicoGrupo');
    }
}